name: ChestPal
main: tf.sou.mc.pal.ChestPal
version: 0.1.0
api-version: 1.17
author: Nils T.


commands:
  chestpal:
    description: Test command for now
    usage: /chestpal
    permission: chestpal.dirttest

  chesttools:
    description: Get receiver and sender tools
    usage: /chesttools
    permission: chestpal.chesttools

permissions:
  chestpal.dirttest:
    description: Allows access to test command
    default: op

  chestpal.chesttools:
    description: Allows access to chesttool command
    default: op

  chestpal.*:
    description: Wildcard access to all chestpal commands
    default: op


